import tkinter as tk
from tkinter import Tk
from tkinter import *
from tkinter import ttk

root = Tk()

L1 = ttk.Style()

# Set the font size for the Entry widget
L1.configure("Entry", font=("Helvetica", 50))

L1 = Entry(root, width=6)
L1.grid(column=0,row=0)
L1 = Entry(root, width=6)
L1.grid(column=0,row=1)
L1 = Entry(root, width=6)
L1.grid(column=0,row=2)
L1 = Entry(root, width=6)
L1.grid(column=0,row=3)
L1 = Entry(root, width=6)
L1.grid(column=0,row=4)

L1 = Entry(root, width=6)
L1.grid(column=1,row=0)
L1 = Entry(root, width=6)
L1.grid(column=1,row=1)
L1 = Entry(root, width=6)
L1.grid(column=1,row=2)
L1 = Entry(root, width=6)
L1.grid(column=1,row=3)
L1 = Entry(root, width=6)
L1.grid(column=1,row=4)

L1 = Entry(root, width=6)
L1.grid(column=2,row=0)
L1 = Entry(root, width=6)
L1.grid(column=2,row=1)
L1 = Entry(root, width=6)
L1.grid(column=2,row=2)
L1 = Entry(root, width=6)
L1.grid(column=2,row=3)
L1 = Entry(root, width=6)
L1.grid(column=2,row=4)

L1 = Entry(root, width=6)
L1.grid(column=3,row=0)
L1 = Entry(root, width=6)
L1.grid(column=3,row=1)
L1 = Entry(root, width=6)
L1.grid(column=3,row=2)
L1 = Entry(root, width=6)
L1.grid(column=3,row=3)
L1 = Entry(root, width=6)
L1.grid(column=3,row=4)

L1 = Entry(root, width=6)
L1.grid(column=4,row=0)
L1 = Entry(root, width=6)
L1.grid(column=4,row=1)
L1 = Entry(root, width=6)
L1.grid(column=4,row=2)
L1 = Entry(root, width=6)
L1.grid(column=4,row=3)
L1 = Entry(root, width=6)
L1.grid(column=4,row=4)

L1 = Entry(root, width=6)
L1.grid(column=5,row=0)
L1 = Entry(root, width=6)
L1.grid(column=5,row=1)
L1 = Entry(root, width=6)
L1.grid(column=5,row=2)
L1 = Entry(root, width=6)
L1.grid(column=5,row=3)
L1 = Entry(root, width=6)
L1.grid(column=5,row=4)

L1 = Entry(root, width=6)
L1.grid(column=6,row=0)
L1 = Entry(root, width=6)
L1.grid(column=6,row=1)
L1 = Entry(root, width=6)
L1.grid(column=6,row=2)
L1 = Entry(root, width=6)
L1.grid(column=6,row=3)
L1 = Entry(root, width=6)
L1.grid(column=6,row=4)

L1 = Entry(root, width=6)
L1.grid(column=7,row=0)
L1 = Entry(root, width=6)
L1.grid(column=7,row=1)
L1 = Entry(root, width=6)
L1.grid(column=7,row=2)
L1 = Entry(root, width=6)
L1.grid(column=7,row=3)
L1 = Entry(root, width=6)
L1.grid(column=7,row=4)

L1 = Entry(root, width=6)
L1.grid(column=8,row=0)
L1 = Entry(root, width=6)
L1.grid(column=8,row=1)
L1 = Entry(root, width=6)
L1.grid(column=8,row=2)
L1 = Entry(root, width=6)
L1.grid(column=8,row=3)
L1 = Entry(root, width=6)
L1.grid(column=8,row=4)

L1 = Entry(root, width=6)
L1.grid(column=9,row=0)
L1 = Entry(root, width=6)
L1.grid(column=9,row=1)
L1 = Entry(root, width=6)
L1.grid(column=9,row=2)
L1 = Entry(root, width=6)
L1.grid(column=9,row=3)
L1 = Entry(root, width=6)
L1.grid(column=9,row=4)

root.mainloop()

